name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo fmt --check

  # This job checks if the PR has any "Depends on #123" lines in its description.
  check-dependencies:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
    steps:
      - uses: actions/checkout@v4
      - name: Check PR dependencies
        uses: gregsdennis/dependencies-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
